import { GoogleGenAI, Type, Schema } from "@google/genai";
import { Course, CourseModule, Quiz } from "../types";

// Initialize Gemini Client
// We assume process.env.API_KEY is available as per instructions.
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

// Constants for Models
const MODEL_REASONING = 'gemini-3-pro-preview';
const MODEL_FAST = 'gemini-2.5-flash';

// Helper to clean JSON string from Markdown code blocks
const cleanJsonString = (str: string): string => {
  let cleaned = str.replace(/```json/g, "").replace(/```/g, "").trim();
  // Attempt to find the first '{' and last '}' to handle potential conversational prefixes
  const firstBrace = cleaned.indexOf('{');
  const lastBrace = cleaned.lastIndexOf('}');
  if (firstBrace !== -1 && lastBrace !== -1) {
    cleaned = cleaned.substring(firstBrace, lastBrace + 1);
  }
  return cleaned;
};

/**
 * Stage 1: The Researcher Agent
 * Uses Google Search to understand the topic and build a syllabus structure.
 */
export const generateCourseSyllabus = async (topic: string): Promise<Course> => {
  const systemInstruction = `
    You are an expert Education Architect and Translator for Bengali learners ("Shikho AI").
    Your goal is to create a structured learning path for a given topic.
    
    1. Structure the course into 4-6 logical modules.
    2. TRANSLATE all titles and descriptions into natural, high-quality Bengali.
    3. Provide the original English title for reference in parenthesis or separate field.
    4. Ensure the content is educational and accurate.
  `;

  try {
    const response = await ai.models.generateContent({
      model: MODEL_REASONING,
      contents: `Create a comprehensive course syllabus for: "${topic}". Focus on practical skills.
      
      You must output a VALID JSON object with the following structure:
      {
        "title": "Course Title in Bengali",
        "description": "Course Overview in Bengali (2-3 sentences)",
        "modules": [
          {
            "id": "module-1",
            "title": "Module Title in Bengali",
            "originalTitle": "Original English Title",
            "description": "Brief summary in Bengali",
            "duration": "10-15 min"
          }
        ]
      }
      
      Do NOT include markdown formatting (like \`\`\`json). Return ONLY the raw JSON string.
      `,
      config: {
        systemInstruction: systemInstruction,
        tools: [{ googleSearch: {} }], // Enable grounding
        // responseSchema is NOT used here to avoid conflict with tools
      },
    });

    // Extract Grounding Metadata (Sources)
    const sources = response.candidates?.[0]?.groundingMetadata?.groundingChunks
      ?.map((chunk: any) => chunk.web?.uri)
      .filter((uri: string) => !!uri) || [];
    
    const uniqueSources = Array.from(new Set(sources)) as string[];

    const jsonStr = cleanJsonString(response.text || "{}");
    let data;
    try {
      data = JSON.parse(jsonStr);
    } catch (e) {
      console.error("JSON Parse Error:", e);
      throw new Error("Received malformed data from the AI.");
    }
    
    // Validate essential fields
    if (!data.modules || !Array.isArray(data.modules)) {
       throw new Error("Invalid course structure generated.");
    }

    return {
      topic,
      title: data.title || topic,
      description: data.description || "A custom course generated by AI.",
      modules: data.modules.map((m: any, index: number) => ({
        ...m,
        id: m.id || `mod-${index}`,
        isLocked: false,
        isCompleted: false,
      })),
      totalModules: data.modules.length,
      completedModules: 0,
      sources: uniqueSources
    };
  } catch (error) {
    console.error("Error generating syllabus:", error);
    throw error;
  }
};

/**
 * Stage 2: The Content Creator/Translator Agent
 * Generates detailed markdown content for a specific module in Bengali.
 */
export const generateModuleContent = async (topic: string, module: CourseModule): Promise<string> => {
  const systemInstruction = `
    You are a friendly and expert Bengali Tutor.
    Write a detailed educational lesson for the module provided.
    
    Guidelines:
    - Language: Bengali (Bangla). Use English for technical terms (e.g., 'DataFrame', 'Loss Function', 'Component') where appropriate, but explain them briefly.
    - Format: Clean Markdown. Use headers (##, ###), bullet points, and code blocks.
    - Tone: Encouraging, clear, and practical.
    - Content: Include conceptual explanations and a small code example (if relevant to the topic).
    - Length: Approximately 300-500 words.
  `;

  const prompt = `
    Course Topic: ${topic}
    Module Title: ${module.originalTitle} (${module.title})
    Module Description: ${module.description}
    
    Please write the full lesson content for this module.
  `;

  try {
    const response = await ai.models.generateContent({
      model: MODEL_REASONING, 
      contents: prompt,
      config: {
        systemInstruction: systemInstruction,
      },
    });

    return response.text || "Content generation failed.";
  } catch (error) {
    console.error("Error generating content:", error);
    return "দুঃখিত, এই মুহূর্তের জন্য কন্টেন্ট লোড করা যাচ্ছে না। অনুগ্রহ করে পরে আবার চেষ্টা করুন। (Error loading content)";
  }
};

/**
 * Stage 3: The Examiner Agent
 * Generates a quiz based on the module content.
 */
export const generateQuiz = async (moduleTitle: string, content: string): Promise<Quiz> => {
  const schema: Schema = {
    type: Type.OBJECT,
    properties: {
      questions: {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          properties: {
            id: { type: Type.STRING },
            question: { type: Type.STRING, description: "Question in Bengali" },
            options: { 
              type: Type.ARRAY, 
              items: { type: Type.STRING },
              description: "4 options in Bengali"
            },
            correctIndex: { type: Type.INTEGER, description: "0-3 index of correct answer" },
            explanation: { type: Type.STRING, description: "Why it is correct (in Bengali)" },
          },
          required: ["id", "question", "options", "correctIndex", "explanation"],
        },
      },
    },
    required: ["questions"],
  };

  try {
    // Truncate content to avoid token limits if extremely long, though Flash handles huge context well.
    const safeContent = content.length > 8000 ? content.substring(0, 8000) + "..." : content;

    const response = await ai.models.generateContent({
      model: MODEL_FAST,
      contents: `Generate 3 multiple-choice questions based on this lesson content: \n\n ${safeContent}`,
      config: {
        responseMimeType: "application/json",
        responseSchema: schema,
      },
    });

    const data = JSON.parse(response.text || "{}");
    return {
      moduleId: "unknown", 
      questions: data.questions || [],
    };
  } catch (error) {
    console.error("Error generating quiz:", error);
    throw new Error("Quiz generation failed.");
  }
};
